"use client";
// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";
import NoSSR from "react-no-ssr";
import { useLocalStorage } from "usehooks-ts";
import { useCompareAndUpateCache } from "@/app/_helpers/helpers";
const roboto = Roboto({ weight: "400", subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useCompareAndUpateCache();

  const [settings] = useLocalStorage<{ theme: number | null }>(
    "userSettings",
    { theme: null },
    { initializeWithValue: false },
  );

  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* :laughycryface: */}
        <NoSSR>
          {settings && (
            <div className="wrapper">
              {settings.theme}
              <Header />
              {children}
            </div>
          )}
        </NoSSR>
      </body>
    </html>
  );
}
